source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PTBalloonView_Example', :exclusive => true do
  pod 'PTBalloonView', :path => '../'
end

target 'PTBalloonView_Tests', :exclusive => true do
  pod 'PTBalloonView', :path => '../'

  
end
